### ISSUE TITLE
For new nodes, there won't be any `byte_rate` property

### ISSUE THREAD

**Issue by sag333ar** [3speaknetwork/video-encoder#1]
It is trying to read `byte_rate` & upon not finding, it is failing. 
resulting into no-video-encode even though encoder-node sufficient & efficient enough.

```
1|video  | jobInfo {"errors":[{"message":"Cannot read property 'byte_rate' of undefined","locations":[{"line":3,"column":9}],"path":["queueJob"]}],"data":{"queueJob":null}} { node_id: 'did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW' }
1|video  | TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | unhandledRejection TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | https://encoder-gateway.infra.3speak.tv
1|video  | jobInfo {"data":{"queueJob":{"reason":"RANK_REQUIREMENT","job":null}}} { node_id: 'did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW' }
1|video  | https://encoder-gateway.infra.3speak.tv
1|video  | jobInfo {"errors":[{"message":"Cannot read property 'byte_rate' of undefined","locations":[{"line":3,"column":9}],"path":["queueJob"]}],"data":{"queueJob":null}} { node_id: 'did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW' }
1|video  | TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | unhandledRejection TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | https://encoder-gateway.infra.3speak.tv
1|video  | jobInfo {"errors":[{"message":"Cannot read property 'byte_rate' of undefined","locations":[{"line":3,"column":9}],"path":["queueJob"]}],"data":{"queueJob":null}} { node_id: 'did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW' }
1|video  | TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | unhandledRejection TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | https://encoder-gateway.infra.3speak.tv
1|video  | jobInfo {"errors":[{"message":"Cannot read property 'byte_rate' of undefined","locations":[{"line":3,"column":9}],"path":["queueJob"]}],"data":{"queueJob":null}} { node_id: 'did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW' }
1|video  | TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|video  | unhandledRejection TypeError: Cannot read properties of null (reading 'job')
1|video  |     at GatewayClient.getNewJobs (/home/sagar/projects/video-encoder/dist/modules/core/gatewayClient.service.js:131:32)
1|video  |     at runMicrotasks (<anonymous>)
1|video  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
### NodeID 
```
did:key:z6Mkh9MYYAPmrUogCmwxxaGxLbwcxWtbWKyATk1TAi6qkicW
```

**Comment by vaultec81** [comment]
Closing as fixed. Please reopen if this issue persists
