### ISSUE TITLE
`CustomPouchError`s with status 4040 

### ISSUE THREAD

**Issue by sag333ar** [3speaknetwork/video-encoder#3]
and now pouch errors
```
5|video  | Error
5|video  |     at new CustomPouchError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:656:21)
5|video  |     at createError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:665:10)
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:5183:25
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4220:9
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4051:13 {
5|video  |   status: 404,
5|video  |   name: 'not_found',
5|video  |   message: 'missing',
5|video  |   error: true,
5|video  |   reason: 'missing',
5|video  |   docId: '0347069f-277e-4d3d-9f79-206b022f6a87'
5|video  | }
5|video  | unhandledRejection Error
5|video  |     at new CustomPouchError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:656:21)
5|video  |     at createError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:665:10)
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:5183:25
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4220:9
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4051:13 {
5|video  |   status: 404,
5|video  |   name: 'not_found',
5|video  |   message: 'missing',
5|video  |   error: true,
5|video  |   reason: 'missing',
5|video  |   docId: '0347069f-277e-4d3d-9f79-206b022f6a87'
5|video  | }
5|video  | Error
5|video  |     at new CustomPouchError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:656:21)
5|video  |     at createError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:665:10)
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:5183:25
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4220:9
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4051:13 {
5|video  |   status: 404,
5|video  |   name: 'not_found',
5|video  |   message: 'missing',
5|video  |   error: true,
5|video  |   reason: 'missing',
5|video  |   docId: '0347069f-277e-4d3d-9f79-206b022f6a87'
5|video  | }
5|video  | unhandledRejection Error
5|video  |     at new CustomPouchError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:656:21)
5|video  |     at createError (/Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:665:10)
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:5183:25
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4220:9
5|video  |     at /Users/sagar/Projects/3speak/video-encoder/node_modules/pouchdb/lib/index.js:4051:13 {
```

**Comment by vaultec81** [comment]
Going to close this as there have bene significant changes relating to the pouchdb datastore since this issue was created.
